select 
    game_id
    ,season
    ,game_type
    ,home_team_abbr
    ,away_team_abbr
    ,home_team_score
    ,away_team_score
    ,home_team_winner
    ,away_team_winner 
from 
    nba.game_summaries 